import type { KiroCatalogModelDefinition } from "./types";

// Capability metadata for Kiro's non-Claude models is still somewhat fluid.
// Until live discovery is reliable for this provider, keep the fallback catalog
// to a small set that has been validated against real Kiro accounts.
export const KIRO_FALLBACK_MODEL_CATALOG = [
  {
    id: "auto",
    name: "Auto",
    serviceModelId: "auto",
    family: "routing",
    reasoning: false,
    inputModalities: ["text"],
    notes: "Auto-routing entry exposed by Kiro; capabilities are conservative placeholders.",
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    serviceModelId: "claude-haiku-4.5",
    family: "claude",
    reasoning: false,
    inputModalities: ["text", "image"],
    contextWindow: 200000,
    maxTokens: 64000,
    notes: "Image support inferred from the OpenCode plugin README; pi does not model PDF input.",
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5",
    serviceModelId: "claude-sonnet-4.5",
    family: "claude",
    reasoning: true,
    inputModalities: ["text", "image"],
    contextWindow: 200000,
    maxTokens: 64000,
  },
  {
    id: "claude-sonnet-4-5-1m",
    name: "Claude Sonnet 4.5 (1M Context)",
    serviceModelId: "claude-sonnet-4.5-1m",
    family: "claude",
    reasoning: true,
    inputModalities: ["text", "image"],
    contextWindow: 1000000,
    maxTokens: 64000,
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    serviceModelId: "claude-sonnet-4.6",
    family: "claude",
    reasoning: true,
    inputModalities: ["text", "image"],
    contextWindow: 200000,
    maxTokens: 64000,
  },
  {
    id: "claude-sonnet-4-6-1m",
    name: "Claude Sonnet 4.6 (1M Context)",
    serviceModelId: "claude-sonnet-4.6-1m",
    family: "claude",
    reasoning: true,
    inputModalities: ["text", "image"],
    contextWindow: 1000000,
    maxTokens: 64000,
  },
  {
    id: "claude-opus-4-5",
    name: "Claude Opus 4.5",
    serviceModelId: "claude-opus-4.5",
    family: "claude",
    reasoning: true,
    inputModalities: ["text", "image"],
    contextWindow: 200000,
    maxTokens: 64000,
  },
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    serviceModelId: "claude-opus-4.6",
    family: "claude",
    reasoning: true,
    inputModalities: ["text", "image"],
    contextWindow: 200000,
    maxTokens: 64000,
  },
  {
    id: "claude-opus-4-6-1m",
    name: "Claude Opus 4.6 (1M Context)",
    serviceModelId: "claude-opus-4.6-1m",
    family: "claude",
    reasoning: true,
    inputModalities: ["text", "image"],
    contextWindow: 1000000,
    maxTokens: 64000,
  },
  {
    id: "minimax-m2.5",
    name: "MiniMax 2.5",
    serviceModelId: "minimax-m2.5",
    family: "minimax",
    reasoning: false,
    inputModalities: ["text"],
    contextWindow: 200000,
    maxTokens: 64000,
  },
  {
    id: "glm-5",
    name: "GLM 5",
    serviceModelId: "glm-5",
    family: "glm",
    reasoning: false,
    inputModalities: ["text"],
    contextWindow: 200000,
    maxTokens: 64000,
    notes: "Service model ID is inferred from the public model name and should be treated as provisional until confirmed by live discovery.",
  },
  {
    id: "qwen3-coder-next",
    name: "Qwen3 Coder Next",
    serviceModelId: "qwen3-coder-next",
    family: "qwen",
    reasoning: false,
    inputModalities: ["text"],
    contextWindow: 256000,
    maxTokens: 64000,
  },
] as const satisfies readonly KiroCatalogModelDefinition[];
