import type { KiroCatalogModelDefinition } from "./types";

// Fallback catalog used when the ListAvailableModels API is unreachable.
// Updated to match `kiro-cli chat --list-models` output as of 2025-07-30.
export const KIRO_FALLBACK_MODEL_CATALOG = [
  {
    id: "auto",
    name: "Auto",
    serviceModelId: "auto",
    family: "routing",
    reasoning: false,
    inputModalities: ["text"],
    notes: "Models chosen by task for optimal usage and consistent quality.",
  },
  {
    id: "claude-opus-5",
    name: "Claude Opus 5",
    serviceModelId: "claude-opus-5",
    family: "claude",
    reasoning: true,
    inputModalities: ["text", "image"],
    contextWindow: 1000000,
    maxTokens: 128000,
    notes: "Experimental preview of Claude Opus 5 model with 1M context window.",
  },
  {
    id: "claude-sonnet-5",
    name: "Claude Sonnet 5",
    serviceModelId: "claude-sonnet-5",
    family: "claude",
    reasoning: true,
    inputModalities: ["text", "image"],
    contextWindow: 1000000,
    maxTokens: 128000,
  },
  {
    id: "claude-opus-4.8",
    name: "Claude Opus 4.8",
    serviceModelId: "claude-opus-4.8",
    family: "claude",
    reasoning: true,
    inputModalities: ["text", "image"],
    contextWindow: 1000000,
    maxTokens: 128000,
  },
  {
    id: "gpt-5.6-sol",
    name: "GPT 5.6 Sol",
    serviceModelId: "gpt-5.6-sol",
    family: "openai",
    reasoning: true,
    inputModalities: ["text"],
    contextWindow: 272000,
    maxTokens: 64000,
    notes: "Experimental preview of OpenAI GPT 5.6 Sol with 272k context window.",
  },
  {
    id: "gpt-5.6-terra",
    name: "GPT 5.6 Terra",
    serviceModelId: "gpt-5.6-terra",
    family: "openai",
    reasoning: true,
    inputModalities: ["text"],
    contextWindow: 272000,
    maxTokens: 64000,
    notes: "Experimental preview of OpenAI GPT 5.6 Terra with 272k context window.",
  },
  {
    id: "gpt-5.6-luna",
    name: "GPT 5.6 Luna",
    serviceModelId: "gpt-5.6-luna",
    family: "openai",
    reasoning: true,
    inputModalities: ["text"],
    contextWindow: 272000,
    maxTokens: 64000,
    notes: "Experimental preview of OpenAI GPT 5.6 Luna with 272k context window.",
  },
  {
    id: "claude-opus-4.7",
    name: "Claude Opus 4.7",
    serviceModelId: "claude-opus-4.7",
    family: "claude",
    reasoning: true,
    inputModalities: ["text", "image"],
    contextWindow: 1000000,
    maxTokens: 128000,
  },
  {
    id: "claude-opus-4.6",
    name: "Claude Opus 4.6",
    serviceModelId: "claude-opus-4.6",
    family: "claude",
    reasoning: true,
    inputModalities: ["text", "image"],
    contextWindow: 1000000,
    maxTokens: 128000,
  },
  {
    id: "claude-sonnet-4.6",
    name: "Claude Sonnet 4.6",
    serviceModelId: "claude-sonnet-4.6",
    family: "claude",
    reasoning: true,
    inputModalities: ["text", "image"],
    contextWindow: 1000000,
    maxTokens: 128000,
  },
  {
    id: "claude-opus-4.5",
    name: "Claude Opus 4.5",
    serviceModelId: "claude-opus-4.5",
    family: "claude",
    reasoning: true,
    inputModalities: ["text", "image"],
    contextWindow: 200000,
    maxTokens: 64000,
  },
  {
    id: "claude-sonnet-4.5",
    name: "Claude Sonnet 4.5",
    serviceModelId: "claude-sonnet-4.5",
    family: "claude",
    reasoning: true,
    inputModalities: ["text", "image"],
    contextWindow: 200000,
    maxTokens: 64000,
  },
  {
    id: "claude-sonnet-4",
    name: "Claude Sonnet 4",
    serviceModelId: "claude-sonnet-4",
    family: "claude",
    reasoning: true,
    inputModalities: ["text", "image"],
    contextWindow: 200000,
    maxTokens: 64000,
    notes: "Hybrid reasoning and coding for regular use.",
  },
  {
    id: "claude-haiku-4.5",
    name: "Claude Haiku 4.5",
    serviceModelId: "claude-haiku-4.5",
    family: "claude",
    reasoning: false,
    inputModalities: ["text", "image"],
    contextWindow: 200000,
    maxTokens: 64000,
  },
  {
    id: "deepseek-3.2",
    name: "DeepSeek 3.2",
    serviceModelId: "deepseek-3.2",
    family: "deepseek",
    reasoning: false,
    inputModalities: ["text"],
    contextWindow: 128000,
    maxTokens: 64000,
    notes: "Experimental preview of DeepSeek V3.2.",
  },
  {
    id: "minimax-m2.5",
    name: "MiniMax M2.5",
    serviceModelId: "minimax-m2.5",
    family: "minimax",
    reasoning: false,
    inputModalities: ["text"],
    contextWindow: 196000,
    maxTokens: 64000,
  },
  {
    id: "minimax-m2.1",
    name: "MiniMax M2.1",
    serviceModelId: "minimax-m2.1",
    family: "minimax",
    reasoning: false,
    inputModalities: ["text", "image"],
    contextWindow: 196000,
    maxTokens: 64000,
    notes: "Experimental preview of MiniMax M2.1.",
  },
  {
    id: "glm-5",
    name: "GLM 5",
    serviceModelId: "glm-5",
    family: "glm",
    reasoning: false,
    inputModalities: ["text"],
    contextWindow: 200000,
    maxTokens: 64000,
  },
  {
    id: "qwen3-coder-next",
    name: "Qwen3 Coder Next",
    serviceModelId: "qwen3-coder-next",
    family: "qwen",
    reasoning: true,
    inputModalities: ["text", "image"],
    contextWindow: 256000,
    maxTokens: 64000,
    notes: "Experimental preview of Qwen3 Coder Next.",
  },
] as const satisfies readonly KiroCatalogModelDefinition[];
